# Generated by Django 4.1 on 2024-03-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_categoryofmeals_meal_restaurant_delete_sushishop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена, р.'),
        ),
        migrations.AddField(
            model_name='meal',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес, г.'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
    ]
