# Generated by Django 4.1 on 2024-03-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_meal_price_meal_weight_alter_meal_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryofmeals',
            options={'verbose_name': 'Категория ресторана', 'verbose_name_plural': 'Категории ресторана'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Ресторан', 'verbose_name_plural': 'Рестораны'},
        ),
    ]
