# Generated by Django 4.1 on 2024-03-25 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurant_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг'),
        ),
    ]
